[package]
name = "kangaroo-lab"
version = "0.1.1"
edition = "2024"

[dependencies]
rand = { version = "0.10.1", features = ["sys_rng"] }
group = {  version = "0.14.0-pre.0", package = "rustcrypto-group" }
ff = { version = "0.14.0-pre.0", package = "rustcrypto-ff", features = ["bitvec"]}
subtle = {  version = "2.6.1", features = ["const-generics"] }
indicatif = { version = "0.18.4" }
clap = { version = "4.6.1", features = ["derive"] }
num-integer = { version = "0.1.46", features = ["i128"]}
k256 = { version = "0.14.0-rc.11", features = ["arithmetic", "expose-field", "precomputed-tables"] }